language: minimal

sudo: false

env:
  global:
    # Doctr deploy key for oceanhackweek/oceanhackweek.github.io
    - secure: "PLB586yCJUjygQpnyE/H8iHRxaNZciDnINW7kx5GRLtBIMNEu5czruL0I60kvC0tCj4e3dIlxD94FiLMn8voT21kuTg5ortWqLkMASH4cfwuwcR1O1lx9aKG4Xb6gLmZk9R6Fy192gyNBWCCIdPamUIZs2o2qpNGAoZzGs9zkO+HnDpQhaNgrkv/KARIsy42k+q6FWMMNpj4nruiCAu7rEw96hMNI1smFGfxyo+9lsHVFd5QpH6qoQeAetS2x2rXDJHtFUQsv73VXr+8vMooGgVtg7vKLfIrxn99G3x66Fq6ZuIYXyXJ1K6SmxwsI8bizHV4Zv2Gzc1iIer473eQM+xyQkS+9ReMVxjBp91uID0ilNPJ5C2bm6m/XRCH9c7SvT6XFcjR2/RQWCkOwyjSxcmOgcYNMsLTRFQ20VnRRS68RxW3mb5zwYse6YNydm1fVUtnSLTMPX8H4XQHtsSwvNpBZT2c0w/WoUUMy9kLHj0ydsM3otstA3rO6xY1FOncgW5h/A7afHxWrHGzXI2V3RYNsL/v/n+uq8LSmmTE5k+yfn8rZ05XaKhTJzgw7ipkQRBOKcwLqSTa5yLLreWpMPfdcDS2qBecLwtNyzJ09ml9WgQBojWyFUtop/87Vdown9unm3TB0dO0Ysj0MokUWS0RBvDAHsN2FouUyKYf6f0="

before_install:
  # Install miniconda and create TEST env.
  - |
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    bash miniconda.sh -b -p $HOME/miniconda
    export PATH="$HOME/miniconda/bin:$PATH"
    conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
    conda update --quiet conda
    conda config --add channels conda-forge --force
    conda config --set channel_priority strict
    conda config --set safety_checks disabled
    conda create --name TEST python=3 rb-bundler compilers doctr
    source activate TEST
    bundle install

install:
  - bundle exec jekyll build --verbose

script:
  - |
    set -e
    if [[ -z "$TRAVIS_TAG" ]]; then
      DEPLOY_DIR=dev
    else
      DEPLOY_DIR="version-$TRAVIS_TAG"
    fi
    python -m doctr deploy --branch-whitelist source --build-tags --key-path github_deploy_key_oceanhackweek_oceanhackweek_github_io.enc --built-docs _site/ $DEPLOY_DIR
    python -m doctr deploy --branch-whitelist source --build-tags --key-path github_deploy_key_oceanhackweek_oceanhackweek_github_io.enc --built-docs _site/ .

doctr:
  require-master: true
  sync: false
