language: minimal

sudo: false

env:
  global:
    # Doctr deploy key for oceanhackweek/oceanhackweek.github.io
    - secure: "ohNS9f2yN1i//vqm4ySiB0wUmZMai/GJDu0FNT7Q3DlaCbwPyg1gbNfi0nEXWmxLjAyEyK67jQfB6BsFZ6zQaUyw07bcb4ugZ+ASRUNncJUfGJzh9Pdhwx0VteMZ+sfaCIQ4ipTJ2I4y2gowwOs0JB0QXOsOrVy77Ozxj0X4FEjdP5Q+yFyEbRucA0teoZd1GXL8fK/71DDcuIn1TnHH/3I1nu3OrBIfmoHSsr9bb8LFp02w+rDSY9d5cXNkFoMPJVvuJRdZ7vAQeX6jxHlILkfs8CPBEs4i9Hkrci7o4AcVbIpGIzQN8apDkGPuuMbqBo9NvCkDZ4Ilq3EzEOme0mXEUaTmCltsS4vlwR0ih0BQ4TzCpKEqwVfc0GBb17URJkbZcJ6DRmHEFU9Y5y98WpfGPEGYVPJvYHM+62vdl19kTcGWpf11HwFsoz12TbcnDnEmVG5ftFGT/z3UVlVipmkKDh4JqgrBifNCMfsKscbd8urNZksYYWWNZ5fQ+JxiYu3O4AHFdYjPmtcylxzfdnwHoTyuvGc7tP8nPVwCYih7RSI4oBsABoOsupI0fE0qOYtlrd1kW3yQY686Jl7gOJQGXniBwD91aPYCXjZC4C2WpROUfnWat1qZNOum0aMci7eWQj+wLqkc9bvX1JQHNd+uHYKNQt6rEJdEMLZFCKI="

before_install:
  # Install miniconda and create TEST env.
  - |
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    bash miniconda.sh -b -p $HOME/miniconda
    export PATH="$HOME/miniconda/bin:$PATH"
    conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
    conda update --quiet conda
    conda config --add channels conda-forge --force
    conda config --set channel_priority strict
    conda config --set safety_checks disabled
    conda create --name TEST python=3 rb-bundler compilers doctr
    source activate TEST
    bundle install

install:
  - bundle exec jekyll build --verbose

script:
  - |
    set -e
    if [[ -z "$TRAVIS_TAG" ]]; then
      DEPLOY_DIR=dev
    else
      DEPLOY_DIR="version-$TRAVIS_TAG"
    fi
    python -m doctr deploy --build-tags --key-path github_deploy_key_oceanhackweek_oceanhackweek_github_io.enc --built-docs _site/ $DEPLOY_DIR
    python -m doctr deploy --build-tags --key-path github_deploy_key_oceanhackweek_oceanhackweek_github_io.enc --built-docs _site/ .

doctr:
  require-master: true
  sync: false
