# Site settings
title: Oceanhackweek 2019
email: oceanhkw@uw.edu
description: Data Science + Oceanography<br>
             University of Washington<br>
             Aug 26-30, 2019 <br> <br>

             Useful resources on the <a href="https://oceanhackweek.github.io/wiki/">Wiki</a>!

# Banner button to lead to form, then schedule, then next year's website.
banner_button_url: projects_2019.html
banner_button_text: 2019 Hack Projects


baseurl: "/ohw19" # the subpath of your site, e.g. /blog
BASE_PATH : /ohw19

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# Misc settings
featured-image-source:

# Social settings
github_url: https://github.com/oceanhackweek
slack_url: https://oceanhackweek.slack.com
email_url: oceanhackweek@uw.edu
500px_url:
facebook_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
twitter_url:

# Build settings
markdown: kramdown

# Submodule setting
destination:  _site/
plugins_dir:  jekyll-spectral-theme/_plugins/
layouts_dir:  jekyll-spectral-theme/_layouts/
includes_dir: jekyll-spectral-theme/_includes/
exclude:
- jekyll-spectral-theme/

include: ["_pages"]
