# Site settings
title: Oceanhackweek 2020
email: oceanhackweek@uw.edu
description: Data Science + Oceanography<br>
             Aug 10-14, 2020<br>
             Two parallel, coordinated events:<br>
             <b>East</b> @ Bigelow Laboratory for Ocean Sciences<br>
             <b>West</b> @ University of Washington<br>
             <br>

             Useful resources on the <a href="https://oceanhackweek.github.io/wiki/">Wiki</a>!

# Banner button to lead to form, then schedule, then next year's website.
banner_button_url: projects_2019.html
banner_button_text: 2019 Hack Projects


baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# Misc settings
featured-image-source:

# Social settings
github_url: https://github.com/oceanhackweek
slack_url: https://oceanhackweek.slack.com
email_url: oceanhackweek@uw.edu
500px_url:
facebook_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
twitter_url:

# Build settings
markdown: kramdown

# Theme setting, we are excluding jekyll-spectral-theme/ root to avoid picking up theme config.
# We should probably clean it up later.
destination:  _site/
plugins_dir:  jekyll-spectral-theme/_plugins/
layouts_dir:  jekyll-spectral-theme/_layouts/
includes_dir: jekyll-spectral-theme/_includes/
exclude:
- jekyll-spectral-theme/

include: ["_pages"]
