# Site settings
title: OceanHackWeek 2021
email: oceanhackweek@uw.edu
description: Data Science + Oceanography<br>
    A hands-on, interactive HYBRID workshop<br>
    August 3-6, 2021<br>
    <b>In person</b> @ Bigelow Laboratory for Ocean Sciences, Maine<br>
    <b>Virtual</b> @ a couple of time zones.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# Misc settings
featured-image-source:

# Social settings
github_url: https://github.com/oceanhackweek
slack_url: https://oceanhackweek.slack.com
email_url: oceanhkw@uw.edu
500px_url:
facebook_url:
instagram_url:
linkedin_url:
pinterest_url:
twitter_url:

# Build settings
markdown: kramdown

# Theme setting, we are excluding jekyll-spectral-theme/ root to avoid picking up theme config.
# We should probably clean it up later.
destination:  _site/
plugins_dir:  jekyll-spectral-theme/_plugins/
layouts_dir:  jekyll-spectral-theme/_layouts/
includes_dir: jekyll-spectral-theme/_includes/
exclude:
- jekyll-spectral-theme/

include: ["_pages"]
