# Site settings
title: Oceanhackweek 2019
email: oceanhkw@uw.edu
description: Data Science + Oceanography <br>
             University of Washington <br>
             Aug. 26 - 30, 2019 <br> <br>
             Accepted applicants will be notified no later than <s May 28.> May 31 <br> (we have delayed the announcement due to an unexpected large number of applications)<br> 


# Banner button to lead to form, then schedule, then next year's website.
banner_button_url: https://form.jotform.com/oceanhack/2019
banner_button_text: Applications are now closed


baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/oceanhackweek
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url: https://oceanhackweek2018.slack.com
twitter_url:
email_url: oceanhkw@uw.edu

# Build settings
markdown: kramdown

# Submodule setting
destination:  _site/
plugins_dir:  jekyll-spectral-theme/_plugins/
layouts_dir:  jekyll-spectral-theme/_layouts/
includes_dir: jekyll-spectral-theme/_includes/
exclude:
- jekyll-spectral-theme/

include: ["_pages"]
