name: Check Jekyll Build
on:
  pull_request:
    branches: [ master ]

jobs:
  # Job to test that web pages build
  jekyll_build:
    name: Jekyll build of web pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build with Jekyll
        uses: jerryjvl/jekyll-build-action@v1

      - name: Upload Website artifact
        uses: actions/upload-artifact@v1
        with:
          name: Website
          path: ./_site/