name: Build and Deploy docs

on: [push, pull_request]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Conda environment from environment.yml
        uses: mamba-org/provision-with-micromamba@v11

      - name: Build documentation
        shell: bash -l {0}
        run: |
          make html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        if: github.ref == 'refs/heads/source' && github.repository == 'oceanhackweek/oceanhackweek.github.io'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
          FOLDER: _build/html
          CLEAN: false
